### PR TITLE
- adds a unit test for ODSP file download with custom request

### LINKED ISSUE #331: GraphClient.customRequest returns a BufferedInputStream instead of a Stream
### Expected behavior
When called with a  `Stream.class` as second parameter, `GraphClient.customRequest` should return a Stream.

### Actual behavior
`GraphClient.customRequest` returns a `java.io.BufferedInputStream` that causes a `ClassCastException`

### Steps to reproduce the behavior

Use the very same code that is shown in the [documentation](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=java).

```java
        String contentRequest = String.format(
                "/drives/%s/items/%s/content",
                DRIVE_ID,
                ITEM_ID
        );

        Stream stream = graphClient.customRequest(contentRequest, Stream.class)
                .buildRequest()
                .get();
```
When executing this code, I am getting a `ClassCastException`.

```
Exception in thread "main" java.lang.ClassCastException: java.io.BufferedInputStream cannot be cast to java.util.stream.Stream
	at com.acmeinc.msgraph.TestSharepointAccess.getFile(TestSharepointAccess.java:249)
	at com.acmeinc.msgraph.TestSharepointAccess.testSharepoint(TestSharepointAccess.java:90)
	at Main.main(Main.java:27)

```

### PR DESCRIPTION
**Pull request by baywet**
Fixes #331

### Changes proposed in this pull request
-

### Other links

-

### CODE REVIEW

File: src/test/java/com/microsoft/graph/functional/OneDriveTests.java [hunk 1]
```diff
@@ -77,5 +78,10 @@ public void failure(final ClientException ex) {
 		
     	chunkedUploadProvider.upload(callback);
     }
-    
+	@Test
+	public void testDownloadWithCustomRequest() throws IOException {
+		final String testDownloadFileId = "01RWFXFJG3UYRHE75RZVFYWKNUEBB53H7A";
+		final InputStream stream = testBase.graphClient.customRequest("/me/drive/items/"+testDownloadFileId+"/content", InputStream.class).buildRequest().get();
```
Comment (zengin) [inline src/test/java/com/microsoft/graph/functional/OneDriveTests.java:84]: We either need an explicit `close()` on the stream or [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) block here.

Comment (baywet) [reply src/test/java/com/microsoft/graph/functional/OneDriveTests.java:84]:
```suggestion
		try (final InputStream stream = testBase.graphClient.customRequest("/me/drive/items/"+testDownloadFileId+"/content", InputStream.class).buildRequest().get()) {
```

File: src/test/java/com/microsoft/graph/functional/OneDriveTests.java [hunk 2]
```diff
@@ -77,5 +78,10 @@ public void failure(final ClientException ex) {
...
+		assertFalse("stream should not be empty", stream.read() == -1);
```
Comment (baywet) [inline src/test/java/com/microsoft/graph/functional/OneDriveTests.java:85]:
```suggestion
		   assertFalse("stream should not be empty", stream.read() == -1);
		}
```

**Review by zengin — APPROVED** [review]
