### PR TITLE
fix serialization of Void for Java 9

### LINKED ISSUE #69: Gson/Jdk 9 serialization warnings
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [X ] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ X] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [ X] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
No serialization warnings on POST 

### Actual behavior
[POSTDraftMessageWarning.zip](https://github.com/microsoftgraph/msgraph-sdk-java/files/1772322/POSTDraftMessageWarning.zip)
NFO: Starting to send request, URL https://graph.microsoft.com/v1.0/me/mailFolders/Drafts/messages/AQMkAGFiMmViMzU2LWExOGEtNGY2YS04MzkzLTE4YTlmNTNkYWEAMWEARgAAA6Rab21vU6xDt5I_G5um6EYHABUsriz4zOpLoeCGQBXajO4AAAMRAAAAFSyuLPjM6kuh4IZAFdqM7gAEd_oxLAAAAA==/microsoft.graph.send
Feb 28, 2018 4:17:25 PM com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Request Method POST
Feb 28, 2018 4:17:25 PM com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Response code 202, Accepted
Feb 28, 2018 4:17:25 PM com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Handling accepted response
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.ConstructorConstructor (file:/C:/Users/johnau/.m2/repository/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar) to constructor java.lang.Void()
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.ConstructorConstructor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Feb 28, 2018 4:17:25 PM com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Deserializing a non-IJsonBackedObject type Void
Feb 28, 2018 4:17:25 PM com.microsoft.graph.logger.DefaultLogger logDebug

### Steps to reproduce the behavior

mGraphServiceClient
                    .me()
                    .mailFolders("Drafts")
                    .messages(messageId)
                    .send()
                    .buildRequest()
                    .post(callback);

### PR DESCRIPTION
**Pull request by davidmoten**
Fixes #69.

When Gson tries to deserialize to a `Void` field it accesses the private constructor of `Void` which is an illegal access in Java 9 (and warnings are written to stdout).

The fix is to add another clause to the `FallbackTypeAdapterFactory` to serialize/deserialize a `Void` object.

I've also 
* renamed `FallBackEnumTypeAdapter` to `FallbackTypeAdapterFactory`
* ensured that `FallbackTypeAdapterFactory` uses the current logger (it was set to use `DefaultLogger`)
* refactored the internals of `FallbackTypeAdapterFactory` to use a concrete class instead of anonymous (this is friendly for users reading stacktraces)
* added a unit test that when run with Java 9 *before* fix produced output like this:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.ConstructorConstructor (file:/home/dxm/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.2/3edcfe49d2c6053a70a2a47e4e1c2f94998a49cf/gson-2.8.2.jar) to constructor java.lang.Void()
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.ConstructorConstructor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

After fix this message did not appear.

To test against Java 9 just have to change build.gradle `sourceCompatibility` and `targetCompatibility` to 1.9 (assumes you have Java 9 installed).

By the way I tried to get the unit test to fail with Java 9 by redirecting `System.err` and `System.out` but this did not work. I assume the JVM is writing these warnings outside of the use of System class.

I'll rebase this once #79 is fixed.

### CODE REVIEW

**Comment by davidmoten** [comment]
This is not a complicated PR, can this be reviewed and merged please?

**Comment by davidmoten** [comment]
I've rebased and updated PR.  Travis failure is due to insufficient memory. May as well disable CI till it's working.

File: src/test/java/com/microsoft/graph/serializer/DefaultSerializerTests.java [hunk 1]
```diff
@@ -99,4 +101,24 @@ public void testDeserializeDerivedType() throws Exception {
...
+    public void testSerializerCanSerializeVoid() {
+        final DefaultSerializer serializer = new DefaultSerializer(new DefaultLogger());
+        Test1 t = new Test1();
+        String json = serializer.serializeObject(t);
+        // this line will emit a warning from Java 9 about illegal access to the constructor of Void 
+        // if gson TypeAdapterFactory is not handling Void properly
+        serializer.deserializeObject(json, Test1.class);
+    }
+  
+  public static final class Test1 {
```
Comment (deepak2016) [inline src/test/java/com/microsoft/graph/serializer/DefaultSerializerTests.java]: Can you give more meaningful name instead of Test1? how about TestClassWithVoidMember

File: src/test/java/com/microsoft/graph/serializer/DefaultSerializerTests.java [hunk 2]
```diff
@@ -99,4 +101,24 @@ public void testDeserializeDerivedType() throws Exception {
...
 	}
+  
+    @Test
+    public void testSerializerCanSerializeVoid() {
+        final DefaultSerializer serializer = new DefaultSerializer(new DefaultLogger());
+        Test1 t = new Test1();
+        String json = serializer.serializeObject(t);
+        // this line will emit a warning from Java 9 about illegal access to the constructor of Void 
+        // if gson TypeAdapterFactory is not handling Void properly
+        serializer.deserializeObject(json, Test1.class);
```
Comment (deepak2016) [inline src/test/java/com/microsoft/graph/serializer/DefaultSerializerTests.java]: Please put asserts to make sure deserialized object is same as expected object.

**Comment by deepak2016** [comment]
Wanted to check if this issue is only for Java 9 or is it applicable to Java 8 as well?

**Comment by deepak2016** [comment]
Have disabled travis CI for java sdk

File: src/test/java/com/microsoft/graph/serializer/DefaultSerializerTests.java (hunk 2 above)
Comment (davidmoten) [reply src/test/java/com/microsoft/graph/serializer/DefaultSerializerTests.java]: Yep ok. Serialization is not actually being tested here but rather the emission of a warning (couldn't assert this as it turned out so manual inspection of log required). I'll rename the test method to make it clearer and chuck in the extra asserts.

File: src/test/java/com/microsoft/graph/serializer/DefaultSerializerTests.java (hunk 1 above)
Comment (davidmoten) [reply src/test/java/com/microsoft/graph/serializer/DefaultSerializerTests.java]: Ok, I'll call it `HasVoidMember`

**Comment by davidmoten** [comment]
>Wanted to check with you if this change is only applicable for Java 9?

As above:

>When Gson tries to deserialize to a Void field it accesses the private constructor of Void which is an illegal access in Java 9 (and warnings are written to stdout).

So this change fixes a problem that we find when we use Java 9+ as the runtime. Java 8 and Java 7 (the current target) are supported as well of course.

Classes have been updated, thanks for review.
