### PR TITLE
bugfix/ref serailization

### LINKED ISSUE #575: Assign manager
### Expected behavior
update user manager

### Actual behavior
return Bad Request

stacktrace:
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220Graph service exception Error code: Request_BadRequest
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220Error message: An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected.
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220PUT https://graph.microsoft.com/v1.0/users/50cd9014-211b-4c65-9131-c5d2499f9d18/manager/$ref
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220SdkVersion : graph-java/v2.4.0
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220Authorization : [PII_REDACTED]
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220{"id":"a75c270f-1668-42e5-b36e-848ae7d20d5b"}
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220400 : Bad Request
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220[...]
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220[Some information was truncated for brevity, enable debug logging for more details]
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: Request_BadRequest
Error message: An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected.

PUT https://graph.microsoft.com/v1.0/users/50cd9014-211b-4c65-9131-c5d2499f9d18/manager/$ref
SdkVersion : graph-java/v2.4.0
Authorization : [PII_REDACTED]
{"id":"a75c270f-1668-42e5-b36e-848ae7d20d5b"}

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
nov 27, 2020 12:54:46 PM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: Servlet.service() for servlet [jsp] in context with path [/Intranet] threw exception [An exception occurred processing JSP page /test.jsp at line 47

44: 	DirectoryObject directoryObject = new DirectoryObject();
45: 	directoryObject.id = "a75c270f-1668-42e5-b36e-848ae7d20d5b";
46: 	
47: 	graphClient.users("50cd9014-211b-4c65-9131-c5d2499f9d18").manager().reference().buildRequest().put(directoryObject);
48: 	
49: %>

Stacktrace:] with root cause
com.microsoft.graph.http.GraphServiceException: Error code: Request_BadRequest
Error message: An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected.

PUT https://graph.microsoft.com/v1.0/users/50cd9014-211b-4c65-9131-c5d2499f9d18/manager/$ref
SdkVersion : graph-java/v2.4.0
Authorization : [PII_REDACTED]
{"id":"a75c270f-1668-42e5-b36e-848ae7d20d5b"}

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:501)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:503)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:423)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:345)
	at com.microsoft.graph.requests.extensions.DirectoryObjectReferenceRequest.put(DirectoryObjectReferenceRequest.java:85)
	at org.apache.jsp.test_jsp._jspService(test_jsp.java:117)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:821)

#### create client:

MsGraphAccessTokenProvider accessTokenProvider = MsGraphAccessTokenProvider //
			.tenantName(tenant) //
			.clientId(clientId) //
			.clientSecret(clientSecret) //
			.refreshBeforeExpiry(5, TimeUnit.MINUTES) //
			.build();

	MsGraphAuthenticationProvider authProvider = MsGraphAuthenticationProvider.from(accessTokenProvider);

	IGraphServiceClient graphClient = GraphServiceClient.builder() //
			.authenticationProvider(authProvider) //
			.buildClient();

#### update user manager:

DirectoryObject directoryObject = new DirectoryObject();
directoryObject.id = "50cd9014-211b-4c65-9131-c5d2499f9d18";
	
graphClient.users("a75c270f-1668-42e5-b36e-848ae7d20d5b").manager().reference().buildRequest().put(directoryObject);

### PR DESCRIPTION
**Pull request by baywet**
fixes #575
- codegen update
- adds a unit test for manager update

### CODE REVIEW

**Comment by baywet** [comment]
@zengin @MIchaelMainer some additional context here. This PR will improve things (for trivial cases) but not fix it definitively. We're coming from a starting point where the payload was not properly formatted (usage of odata.id) and no references call would work at all. With this PR we get to a state where some of them will work, some still won't, and that's because the solution is not building the odata id properly. Here is the list of the faulty entity types:
- approleassignment: under user & group but no root collection
- CertificateBasedAuthConfigurations: under organisation/orgid
- ClaimsMappingPolicys/HomeRealmDiscoveryPolicys/TokenIssuancePolicys -> under policies singleton + bad pluralization
- EducationClass/Schools/Users -> under education singleton + not using the full class name + bad pluralization for classes
- Endpoints -> under group
- ItemActivityStats/ItemAnalyticss -> no root collection + bad pluralization
- ManagedAppRegistrations/ManagedDeviceOverviews/ManagedDevices/MobileAppCategorys/RoleDefinitions/SoftwareUpdateStatusSummarys: under deviceAppManagement singleton + some bad pluralization
- TeamsAppDefinitions/TeamsTemplates: no root collection?
- TeamsAppDefinitions -> under appcatalogs singleton
- UserAcivitys -> under /me + bad pluralization

If I think the pluralization issues (ends with y or s) are fixable, and that we can potentially imagine adding some dirty exceptions in the cases where it's not the full class name that is in use, we're left with two major issues:
- the cases that are under a singleton: I'm not sure how to determine that at code-gen time without adding quite some complexity
- the cases that don't have a root collection, what are we supposed to do then?

Before investing more time into this, I wanted to check with you guys the following:
- what's the status of $ref requests (PUTS) in dotnet? are we covering all the entities and edge cases I mentioned above or is it best effort as well?
- any idea for the singleton/namespaces cases?
- would it be ok to get this PR in as an improvement even though it doesn't address about half the entities properly still ? (brings support for all the identity objects that are otherwise broken today/50% improvement over current situation)

Thanks for your opinions!

**Comment by baywet** [comment]
After discussing with @darrelmiller it might be feasible:
- the navigation property we're in has a target attribute which gives the target entity set to use
- getting that target entity set would tell us whether it's contained within a singleton
- using the target entity set name and the singleton name, we should be able to get the correct path

**Comment by baywet** [comment]
Also, after further discussions, it appears we're generating too much (approleassignement, endpoints). When the navigation property is ContainsTarget=True, it should not be generated.

**Comment by baywet** [comment]
@zengin @MIchaelMainer this is ready for review

File: src/main/java/com/microsoft/graph/requests/extensions/AppRoleAssignmentReferenceRequest.java [hunk 1]
```diff
@@ -15,6 +15,8 @@
 import com.microsoft.graph.http.BaseRequest;
 import com.microsoft.graph.http.HttpMethod;
 import com.microsoft.graph.core.IBaseClient;
+import com.google.gson.JsonPrimitive;
+import com.google.gson.JsonObject;
 
 // **NOTE** This file was generated by a tool and any changes will be overwritten.
```
Comment (zengin) [inline src/main/java/com/microsoft/graph/requests/extensions/AppRoleAssignmentReferenceRequest.java:22]: I think that we don't need to generate this file at all given that all instances of AppRoleAssignments are `ContainsTarget=true`.

**Review by zengin — APPROVED** [review]

File: src/main/java/com/microsoft/graph/requests/extensions/AppRoleAssignmentReferenceRequest.java (hunk 1 above)
Comment (baywet) [reply src/main/java/com/microsoft/graph/requests/extensions/AppRoleAssignmentReferenceRequest.java]: thanks for catching that, it was on my todo list to review it but I somehow forgot...
You'll see that in the recent commits I pushed, the return type of propertyAsSomething methods (cast) changed. That's because the initial iteration of the odata cast implementation was wrongly introducing a lot of reference things in the mix.
Because this could be a potentially breaking change to people who might have already started using casting, I'll rebase on v3. Hold any review for now please.

File: src/test/java/com/microsoft/graph/functional/UserTests.java [hunk 2]
```diff
@@ -249,6 +247,22 @@ public void castTest() {
 	@Test
 	public void getMeTransitiveReferences() {
 		DirectoryObjectCollectionWithReferencesPage page = graphServiceClient.me().transitiveMemberOf().references().buildRequest().get();
-		assertNotNull(page);
+        assertNotNull(page);
+    }
+    @Test
+	public void setMyBoss() {
```
Comment (zengin) [inline src/test/java/com/microsoft/graph/functional/UserTests.java:253]: :)

**Review by zengin — APPROVED** [review]
