### PR TITLE
- fixes an issue where receiving no content responses for collections would cause an NPE

### LINKED ISSUE #595: HttpResponseCode.HTTP_NOBODY may cause NullPointerException when EventCollectionRequest.get()
### Expected behavior
No Exception even though the Http response code is HttpResponseCode.HTTP_NOBODY(204)

### Actual behavior
java.lang.NullPointerException
	at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1028)
	at java.util.Collections$UnmodifiableList.<init>(Collections.java:1304)
	at java.util.Collections.unmodifiableList(Collections.java:1289)
	at com.microsoft.graph.http.BaseCollectionPage.<init>(BaseCollectionPage.java:71)
	at com.microsoft.graph.http.BaseCollectionPage.<init>(BaseCollectionPage.java:83)
	at com.microsoft.graph.requests.extensions.EventCollectionPage.<init>(EventCollectionPage.java:26)
	at com.microsoft.graph.requests.extensions.EventCollectionRequest.buildFromResponse(EventCollectionRequest.java:161)

### Steps to reproduce the behavior
I am adding an inteceptor to prevent too big reponse data, after I changed the response code to 204 in the http client inteceptor and use the EventCollectionRequest.get() method to get empty body, the SDK throws NPE.

image
image
image

### PR DESCRIPTION
**Pull request by baywet**
fixes #595

### CODE REVIEW

**Review by nikithauc — DISMISSED** [review]

File: src/main/java/com/microsoft/graph/http/BaseCollectionPage.java [hunk 1]
```diff
@@ -66,9 +67,13 @@
...
-        // CollectionPages are never directly modifiable, either 'update'/'delete' the specific child or 'add' the new
-        // object to the 'children' of the collection.
-        this.pageContents = Collections.unmodifiableList(pageContents);
+        if(pageContents == null) {
+            this.pageContents = new ArrayList<T1>();
+        } else {
+            // CollectionPages are never directly modifiable, either 'update'/'delete' the specific child or 'add' the new
+            // object to the 'children' of the collection.
+            this.pageContents = Collections.unmodifiableList(pageContents);
+        }
```
Comment (zengin) [inline src/main/java/com/microsoft/graph/http/BaseCollectionPage.java:76]: Q: Any reason why we shouldn't keep the immutable behavior for the edge case?

```suggestion
        // CollectionPages are never directly modifiable, either 'update'/'delete' the specific child or 'add' the new
        // object to the 'children' of the collection.
        this.pageContents = Collections.unmodifiableList(pageContents == null ? new ArrayList<T1>() : pageContents);
```

**Review by zengin — CHANGES_REQUESTED** [review]

File: src/main/java/com/microsoft/graph/http/BaseCollectionPage.java (hunk 1 above)
Comment (baywet) [reply src/main/java/com/microsoft/graph/http/BaseCollectionPage.java]: yep, no particular reason, I don't know why I didn't go with this to start with. Thanks!

**Review by zengin — APPROVED** [review]

**Review by MIchaelMainer — APPROVED** [review]
