### PR TITLE
- fixes a bug where downloading json files from onedrive would cause a cast exception

### LINKED ISSUE #275: Error when trying to download .JSON files from OneDrive
I am trying to download a .json file from OneDrive. The following request patterns get the intended behavior (the file is downloaded) for other file types but none work for .json files.
InputStream driveItemInputStream = getGraphServiceClient().drives(driveId).items(driveItemId).content().buildRequest().get();
InputStream driveItemInputStream = getGraphServiceClient().drives().byId(driveId).items().byId(driveItemId).content().buildRequest().get();
InputStream driveItemInputStream = getGraphServiceClient().customRequest(("/drives/"+driveId+"/items/"+driveItemId+"/content"), InputStream.class).buildRequest().get();

Expected behavior
For the file to be downloaded.
Actual behavior
Error response:
com.microsoft.graph.core.ClientException: Error during http request
at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:368)
	at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:204)
	at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:184)
	at com.microsoft.graph.http.BaseStreamRequest.send(BaseStreamRequest.java:81)
	at com.microsoft.graph.requests.extensions.DriveItemStreamRequest.get(DriveItemStreamRequest.java:55)
...
Caused by: java.lang.RuntimeException: Failed to invoke public java.io.InputStream() with no args
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:113)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:78)
	at com.microsoft.graph.http.DefaultHttpProvider.handleJsonResponse(DefaultHttpProvider.java:417)
	at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:342)
	... 46 more

Steps to reproduce the behavior
Use the SDK to make a GET request on a .json file in a user or group OneDrive using any of the request patterns above.
[AB#6032](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6032)

### PR DESCRIPTION
**Pull request by baywet**
Fixes #275

### Changes proposed in this pull request
-

### Other links

-

### CODE REVIEW

File: src/main/java/com/microsoft/graph/http/CoreHttpProvider.java [hunk 1]
```diff
@@ -417,20 +417,20 @@ public Request authenticateRequest(Request request) {
 
 				final Map<String, String> headers = CoreHttpProvider.getResponseHeadersAsMapStringString(response);
 
+				if(response.body() == null || response.body().contentLength() == 0)
```
Comment (zengin) [inline src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:420]: minor perf: if `body()` is more than a simple property access, consider saving a reference to that into a variable to avoid calling it twice. If it is property access, the overhead should be minimal, so you can ignore this comment in that case.

File: src/main/java/com/microsoft/graph/http/CoreHttpProvider.java [hunk 2]
```diff
@@ -417,20 +417,20 @@ public Request authenticateRequest(Request request) {
...
+					return (Result) null;
+
 				final String contentType = headers.get(Constants.CONTENT_TYPE_HEADER_NAME);
-				if (contentType != null && contentType.contains(Constants.JSON_CONTENT_TYPE)) {
+				if (contentType != null && resultClass != InputStream.class && 
+							(contentType.contains(Constants.JSON_CONTENT_TYPE) || contentType.contains(Constants.TEXT_CONTENT_TYPE))) { // some services reply in text/plain with a JSON representation...
```
Comment (zengin) [inline src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:425]: interesting, is there any proper non-JSON `text/plain` response from the services?

File: src/main/java/com/microsoft/graph/http/CoreHttpProvider.java (hunk 1 above)
Comment (baywet) [reply src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:420]: thanks for double checking. I had checking for that and it's simply an accessor to a private field.

File: src/main/java/com/microsoft/graph/http/CoreHttpProvider.java (hunk 2 above)
Comment (baywet) [reply src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:425]: file upload on a $value sometimes replies with a representation of the json object but in text plain (I don't remember which one right now though)

Comment (baywet) [reply src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:425]: and re-reading the question I don't think I'm answering the question. I haven't seen a text/plain response with actual text. But it might be possible. Uploadprofile picture replies with 200 ok of type text/plain but the body is empty

Comment (zengin) [reply src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:425]: yeah, the concern is whether we ever end up trying to parse a non-JSON text/plain response as JSON.

Comment (baywet) [reply src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:425]: would you remove it or then or fail gracefully?

Comment (zengin) [reply src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:425]: I found a case where it can be `text/plain` without being a JSON response. If an attachment is a plain text file, `https://graph.microsoft.com/v1.0/me/messages/<message_id>/attachments/<attachment_id>/$value` returns a `text/plain` response. That will be a problem when we attempt to parse a text file as JSON.

I think the solution should be to have the service team to return correct `Content-Type` and us to have another `else if` block for handling plain text.

File: src/main/java/com/microsoft/graph/http/CoreHttpProvider.java [hunk 3]
```diff
@@ -417,20 +417,20 @@ public Request authenticateRequest(Request request) {
...
 					logger.logDebug("Response binary");
 					isBinaryStreamInput = true;
-					if (resultClass == InputStream.class) {
-						return (Result) handleBinaryStream(in);
-					} else if(response.body() != null && response.body().contentLength() > 0) { // some services reply in text/plain with a JSON representation...
-						return handleJsonResponse(in, CoreHttpProvider.getResponseHeadersAsMapOfStringList(response), resultClass);
-					} else {
-						return (Result) null;
-					}
+					return (Result) handleBinaryStream(in);
```
Comment (nikithauc) [inline src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:431]: The sendRequestInternal() function is a long function. I would recommend breaking them into smaller parts. Example -> introduced a smaller function to handle different response types and call that in sendRequestInternal()

File: src/test/java/com/microsoft/graph/functional/OneDriveTests.java [hunk 4]
```diff
@@ -85,4 +87,18 @@ public void testDownloadWithCustomRequest() throws IOException {
 		   assertFalse("stream should not be empty", stream.read() == -1);
 		}
 	}
+	@Test
+	public void downloadJsonFileFromOneDrive() throws Exception {
+		final InputStream stream = testBase.graphClient.me()
+		.drive()
+		.root()
+		.itemWithPath("test.json")
```
Comment (nikithauc) [inline src/test/java/com/microsoft/graph/functional/OneDriveTests.java:95]: Where is this test.json file located?

File: src/main/java/com/microsoft/graph/core/Constants.java [hunk 5]
```diff
@@ -17,6 +17,10 @@ private Constants() {
 	 * The content type for JSON responses
 	 */
 	public static final String JSON_CONTENT_TYPE = "application/json";
+	/**
+	 * The content type for text responses
+	 */
+	public static final String TEXT_CONTENT_TYPE = "text/plain";
```
Comment (baywet) [inline src/main/java/com/microsoft/graph/core/Constants.java:23]:
```suggestion
```

File: src/main/java/com/microsoft/graph/core/Constants.java [hunk 6]
```diff
@@ -17,6 +17,10 @@ private Constants() {
 	 * The content type for JSON responses
 	 */
 	public static final String JSON_CONTENT_TYPE = "application/json";
+	/**
+	 * The content type for text responses
+	 */
```
Comment (baywet) [inline src/main/java/com/microsoft/graph/core/Constants.java:22]:
```suggestion
```

File: src/main/java/com/microsoft/graph/core/Constants.java [hunk 7]
```diff
@@ -17,6 +17,10 @@ private Constants() {
 	 * The content type for JSON responses
 	 */
 	public static final String JSON_CONTENT_TYPE = "application/json";
+	/**
+	 * The content type for text responses
```
Comment (baywet) [inline src/main/java/com/microsoft/graph/core/Constants.java:21]:
```suggestion
```

File: src/main/java/com/microsoft/graph/core/Constants.java [hunk 8]
```diff
@@ -17,6 +17,10 @@ private Constants() {
 	 * The content type for JSON responses
 	 */
 	public static final String JSON_CONTENT_TYPE = "application/json";
+	/**
```
Comment (baywet) [inline src/main/java/com/microsoft/graph/core/Constants.java:20]:
```suggestion
```

File: src/main/java/com/microsoft/graph/http/CoreHttpProvider.java (hunk 2 above)
Comment (baywet) [reply src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:425]:
```suggestion
							contentType.contains(Constants.JSON_CONTENT_TYPE)) {
```

File: src/main/java/com/microsoft/graph/http/CoreHttpProvider.java (hunk 3 above)
Comment (baywet) [reply src/main/java/com/microsoft/graph/http/CoreHttpProvider.java:431]: I agree on the fact we could/should break that method further down in smaller pieces. However I don't want to introduce too many changes at a time for traceability purposes. Extracting getHttpRequest already divided the method's length by 2 :)

File: src/test/java/com/microsoft/graph/functional/OneDriveTests.java (hunk 4 above)
Comment (baywet) [reply src/test/java/com/microsoft/graph/functional/OneDriveTests.java]: this unit test assumed it'd already be here. I was unclear on how we arrange our integration testing environment so I didn't want to make the "test too big for no reason". But following the discussion we had on Monday, it's clear that we don't have something clearly defined yet, so I'll keep this in mind and write tests that are a little more self sufficient, even if there is redundancy. I just added arragement at the beginning of the test to upload the file we'll need to download.

**Review by zengin — APPROVED** [review]
